# Functions

In [ ]:
# def function


def sqr(num):
   result = num**2
   return result

In [ ]:
sqr(10)

100

In [17]:
def num_status(n):
  if n>0:
    if n%2==0:
      return "Even"
    else:
      return "Odd"
  else:
      return "Low value, Enter the number again!"

In [19]:
print(num_status(5))

Odd


In [29]:
# ques: create a function to return a proper table of given number.

def multiplication_table(num):
    print(f"Multiplication Table of {num}")
    print("-" * 30)
    for i in range(1, 11):
        print(f"{num} x {i} = {num * i}")

In [30]:
multiplication_table(5)

Multiplication Table of 5
------------------------------
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [32]:
# Numpy


import  numpy as np

In [33]:
arr1 = np.array([2,3,4,5,6])
print(arr1)

[2 3 4 5 6]


In [34]:
arr = [10, 20, 30, 40, 50]

print("Elements of the array:")
for i in arr:
    print(i)


Elements of the array:
10
20
30
40
50


In [35]:
# zero

zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
# one

one = np.ones(8)
print(one)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [37]:
# array range


seq = np.arange(1,10,3)
print(seq)

[1 4 7]


In [40]:
#  2-d array
arr2=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(arr2)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
