
# 2-d and 3-d array



In [20]:
# print a 2-d array with values like[90,80,70,60] [300,200,100,400].
import numpy as np
a2d = np.array([[90,80,70,60],[300,200,100,400]])
print(a2d)


[[ 90  80  70  60]
 [300 200 100 400]]


In [2]:
print(type(a2d))


<class 'numpy.ndarray'>


In [8]:
print(a2d.ndim)

2


In [9]:
print(a2d.shape)

(2, 4)


In [11]:
# how to create a 3-d array


arr3 = np.array([
    [[1,2,3],[4,5,6]],
    [[10,20,30],[40,50,60]],
    [[0,0,0],[1,1,1]]
    ])

print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]

 [[ 0  0  0]
  [ 1  1  1]]]


In [5]:
print(type(arr3))


<class 'numpy.ndarray'>


In [6]:
print(arr3.ndim)

3


In [10]:
print(arr3.shape)

(2, 2, 3)


In [12]:
# how to create array using aranger()


arr5 = np.arange(1,10)
print(arr5)

[1 2 3 4 5 6 7 8 9]


In [13]:
arr6 = np.arange(11,50,3)
print(arr6)

[11 14 17 20 23 26 29 32 35 38 41 44 47]


In [14]:
# how to create a 2 dimensional array using arange and reshape


arr7 = np.arange(1,16).reshape(5,3)
print(arr7)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [15]:
# print an array values between 1 and 100and reshape it as per your choice


import numpy as np

# Create array from 1 to 100
arr = np.arange(1, 101)

# Reshape the array (10 rows, 10 columns)
reshaped_arr = arr.reshape(10, 10)

# Print the reshaped array
print(reshaped_arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [19]:
 # print an  array from 101 to 500 and skip 2 digits and reshape it into 5 decsk atleast.
# reshape(d,r,c)


arr9 = np.arange(101,501,2).reshape(5,5,8)
print(arr9)
print(arr9.shape)



[[[101 103 105 107 109 111 113 115]
  [117 119 121 123 125 127 129 131]
  [133 135 137 139 141 143 145 147]
  [149 151 153 155 157 159 161 163]
  [165 167 169 171 173 175 177 179]]

 [[181 183 185 187 189 191 193 195]
  [197 199 201 203 205 207 209 211]
  [213 215 217 219 221 223 225 227]
  [229 231 233 235 237 239 241 243]
  [245 247 249 251 253 255 257 259]]

 [[261 263 265 267 269 271 273 275]
  [277 279 281 283 285 287 289 291]
  [293 295 297 299 301 303 305 307]
  [309 311 313 315 317 319 321 323]
  [325 327 329 331 333 335 337 339]]

 [[341 343 345 347 349 351 353 355]
  [357 359 361 363 365 367 369 371]
  [373 375 377 379 381 383 385 387]
  [389 391 393 395 397 399 401 403]
  [405 407 409 411 413 415 417 419]]

 [[421 423 425 427 429 431 433 435]
  [437 439 441 443 445 447 449 451]
  [453 455 457 459 461 463 465 467]
  [469 471 473 475 477 479 481 483]
  [485 487 489 491 493 495 497 499]]]
(5, 5, 8)
